name: bioconda import

on: push


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        repository: bioconda/bioconda-recipes
        path: bioconda
    - uses: actions/checkout@v2
      with:
        path: content
    - name: import bioconda tools
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/content/data

        if ${{ github.workspace }}/content/scripts/git-utils/is_pr_created.sh checkout-pr-if-exist.sh; then
          IS_PR_CREATED=true
        else
          IS_PR_CREATED=false
        fi

        # Run importing script
        sudo pip3 install virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate
        pip3 install setuptools wheel jinja2 pyyaml
        python3 ${{ github.workspace }}/content/scripts/bioconda-import/bioconda_importer.py ${{ github.workspace }}/content/data/ ${{ github.workspace }}/bioconda/recipes/

        ${{ github.workspace }}/content/scripts/git-utils/update-import.sh $IS_PR_CREATED

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          .venv/
        key: ${{ runner.os }}-bioconda-import
