name: import bio.tools contents

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: geertvdc/setup-hub@master
    - name: import bio.tools using the API
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt install python3-pip
        sudo apt install python3-setuptools
        sudo pip3 install virtualenv 
        virtualenv -p python3 venv
        . venv/bin/activate
        pip install wheel
        pip install -r scripts/biotools-import/requirements.txt
        cd scripts/biotools-import
        python import.py
        git config --local user.email "tpe-bot@github.com"
        git config --local user.name "Tools Platform Ecosystem bot"
        cd ../../data
        git add .
        if git commit -m "import from bio.tools on $(date)"; then
          git push --set-upstream origin "biotools_dump_${{ github.run_id }}"
          hub pull-request -m "import from bio.tools on $(date)"
          echo "successfully created new data"
        else
            echo "nothing new to add, exiting"
        fi