name: import bio.tools using composite

on:
  workflow_dispatch:

jobs:
  import-biotools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bio-tools/content-ecosystem-utils/biotools-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

