name: import bio.tools

on:
  push

jobs:
  import-biotools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: content
    - uses: actions/checkout@v2
      with:
        repository: bio-tools/content-ecosystem-utils
        path: content-ecosystem-utils
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install dependencies
      run:
        pip install -r scripts/biotools-import/requirements.txt
    - name: import bio.tools using the API
      run: |
        cd ${{ github.workspace }}/content/data
        if ${{ github.workspace }}/content-ecosystem-utils/scripts/git-utils/checkout-pr-if-exist.sh bioconda-import; then
          IS_PR_CREATED=true
        else
          IS_PR_CREATED=false
        fi

        cd ${{ github.workspace }}/content-ecosystem-utils/scripts/biotools-import
        python import.py

        echo "IS_PR_CREATED=$IS_PR_CREATED" >> $GITHUB_ENV

    - name: commit new data and push to PR
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/content/data
        #test
        echo "test" >>  ${{ github.workspace }}/content/data/3-d-density-kernel-estimation/3-d-density-kernel-estimation.neubias.bioschemas.jsonld

        ${{ github.workspace }}/content-ecosystem-utils/scripts/git-utils/import-changes.sh $IS_PR_CREATED bioconda-import
