 
name: spread doi among sources

on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 20 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: spread doi among sources
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt install python3-pip
        sudo apt install python3-setuptools
        sudo pip3 install virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate	
        pip3 install setuptools wheel
        pip3 install ruamel.yaml
        pwd
        cd scripts/doi-collector
        python3 doi_collector.py $GITHUB_WORKSPACE/data/
        echo "configuring user email"
        git config --local user.email "tpe-bot@github.com"
        echo "configuring user name"
        git config --local user.name "Tools Platform Ecosystem bot"
        echo "commit"
        git commit -a -m "spread doi amongs sources"
        echo "push"
        git push origin master
